# Generated by Django 3.0.1 on 2020-01-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200105_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
