# Generated by Django 3.0.3 on 2020-03-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
