# Generated by Django 3.0.3 on 2020-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_category_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('def', 'Default'), ('cus', 'Custom')], default='cus', max_length=3, verbose_name='Type'),
        ),
    ]
